name: 'Github Branch Gitee'
description: '同步 GitHub 指定分支到 Gitee'
inputs:
  gitee_repo:
    description: 'Gitee 仓库，例如 username/repo'
    required: true
  gitee_branch:
    description: 'Gitee 分支，例如 master'
    required: true
  username:
    description: 'Gitee 用户名，用于登录。'
    required: true
  password:
    description: 'Gitee 密码，用于登录。'
    required: true
  target_dir:
    description: '生成目录'
    required: true
runs:
  using: composite
  steps:
    - run: |
        git clone -b ${{ inputs.gitee_branch }} https://${{ inputs.username }}:${{ inputs.password }}@gitee.com/${{ inputs.gitee_repo }}.git ${{ inputs.target_dir }}
        git show-ref
        git branch --verbose
      shell: bash
